### ISSUE TITLE
display course-list on myCourses 

### ISSUE THREAD

**Issue by leomaxi** [ole-vi/takeout#109]

**Comment by akshayuncc** [comment]
Work in progress. As soon as other PR are merged I will push my this PR. If someone is ahead they can please go ahead and complete this issue.
Thank you

**Comment by leomaxi** [comment]
Ideally, you should have something like this.. 
<img width="1422" alt="screen shot 2018-07-23 at 10 07 59 pm" src="https://user-images.githubusercontent.com/2836302/43105595-fd60936c-8ec4-11e8-8cf1-76c79de9c4b1.png">
