### ISSUE TITLE
Saving Username And Password @ Login

### ISSUE THREAD

**Issue by Sriharsha-Singam** [ole-vi/takeout#164]
Is this alright? I know it is not in the Web version of planet but I think it would be a good addition to the Android App.

**Comment by leomaxi** [comment]
I think it is saved in SharedPreferences in android (ProcessData.java) 
<img width="690" alt="screen shot 2018-08-02 at 8 36 06 am" src="https://user-images.githubusercontent.com/2836302/43583982-21741550-962f-11e8-836a-719dbba42d7d.png">

**Comment by Sriharsha-Singam** [comment]
So can I go ahead with this issue? @leomaxi
