### ISSUE TITLE
On click myLibrary item error

### ISSUE THREAD

**Issue by rrijal53** [ole-vi/takeout#202]
Video player page is opened if we click on the library item that is not downloaded.

**Comment by Sriharsha-Singam** [comment]
Yes, I am going to fix that with a different issue: #161

**Comment by leomaxi** [comment]
Lets handle the error's. When user clicks on an item and it throws an error, Lets catch the error and later print out a meaning-full message like.. `Resource can not be opened / Or item clicked is not working.. Please inform administrator`
