### ISSUE TITLE
better login

### ISSUE THREAD

**Issue by xyb994** [ole-vi/takeout#42]
- it should not have so much padding blue background on smaller screens
- gear icon on the upper right is not positioned correctly ([screenshot](https://user-images.githubusercontent.com/7483137/40565376-638b1658-603a-11e8-80ae-dd18e00f304a.png))

**Comment by leomaxi** [comment]
It doesn't look good on larger screens... Each screen size must have its custom design.. 

![screenshot_1527322216](https://user-images.githubusercontent.com/2836302/40579969-302e93d0-6124-11e8-9b14-e0b8195460a5.png)
![screenshot_1527322243](https://user-images.githubusercontent.com/2836302/40579970-3622e9da-6124-11e8-89ad-763e91b60694.png)

**Comment by onlyserenity** [comment]
@leomaxi Alright, I will adjust each layout. Thanks for the feedback.

**Comment by onlyserenity** [comment]
PR approved and merged. (PR #46)
