### ISSUE TITLE
add sync feedback on login screen

### ISSUE THREAD

**Issue by leomaxi** [ole-vi/takeout#49]

**Comment by leomaxi** [comment]
Basic => Show a hidden clickable text / button to trigger sending usage feedback data to server. 
Advance => Display a dialogue to turn on auto feedback sync / off

**Comment by onlyserenity** [comment]
![screenshot_1527825582](https://user-images.githubusercontent.com/19535323/40820492-d5466060-652e-11e8-8133-9b23978161de.png)
![screenshot_1527825584](https://user-images.githubusercontent.com/19535323/40820493-d636c01e-652e-11e8-8e8e-a274cdfaac10.png)

**Comment by leomaxi** [comment]
Awesome.. Please make a Pull Request
