### ISSUE TITLE
embedded video player 

### ISSUE THREAD

**Issue by leomaxi** [ole-vi/takeout#58]
Must be able to play almost all types of video files

**Comment by onlyserenity** [comment]
@leomaxi I found [ExoPlayer ](https://github.com/google/ExoPlayer) and it seems to [support ](https://google.github.io/ExoPlayer/supported-formats.html)almost all video file types

**Comment by leomaxi** [comment]
Great.. Go ahead and implement it

**Comment by leomaxi** [comment]
How far with this issue? @onlyserenity
