### ISSUE TITLE
hard to click sync and setting at login

### ISSUE THREAD

**Issue by xyb994** [ole-vi/takeout#64]
Sometimes it's a bit hard to click on sync and setting icon on login screen.

 ![screenshot](https://user-images.githubusercontent.com/7483137/41130557-531acf34-6a85-11e8-944a-55fd4ad5dd61.png)

**Comment by onlyserenity** [comment]
Yes, I too realized they are a bit hard to click. Should I make the "Sync" a button and make the "Gear" icon bigger?
