### ISSUE TITLE
download file from http / https

### ISSUE THREAD

**Issue by leomaxi** [ole-vi/takeout#66]
Download files from http / https address (couchdb attachment file) unto local drive on Android device.
Process must queue multiple downloads
Show download process 
Prompt / alert user when download is completed

**Comment by onlyserenity** [comment]
@leomaxi I can use `AsyncTask `(Update UI and have multiple tasks in background) and use `DownloadManager `class to download and save it on the internal storage of the device. 
I just have two questions to plug what I wrote so far:

* Where should this be implemented? (Drawer, action bar, login activity... etc?
* Are the links to those urls are fixed or the user must enter them manually?

**Comment by leomaxi** [comment]
Please implement this on the dashboard fragment activity (users will see their materials in my library and can click to download it offline )
The links to the online server files will be from the database and will be fixed.. After download, we will save the local file URL in a local database for access.
