### ISSUE TITLE
change colorPrimary to match planet web version?

### ISSUE THREAD

**Issue by xyb994** [ole-vi/takeout#83]

**Comment by gowiredu** [comment]
Is this okay?

![gowiredu-color-primary-1](https://user-images.githubusercontent.com/10681719/42106555-765447b8-7ba2-11e8-96ba-bbea7225829a.jpg)
![gowiredu-color-primary-2](https://user-images.githubusercontent.com/10681719/42106556-766d3016-7ba2-11e8-86ed-4ac3fcc9ad95.jpg)

**Comment by xyb994** [comment]
@gowiredu Looks good, you took the color from planet?

**Comment by xyb994** [comment]
@gowiredu I see, so it's already in the xml. I just checked it's the same `#2196f3`.

**Comment by leomaxi** [comment]
Exactly.. Same colour. Go ahead with A PR

**Comment by aakarnik** [comment]
@gowiredu I like the second one - same color for both, the text and the icon :)
